Vagrant.configure(2) do |config|
  # Specifying the box we wish to use
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "pg-1" do |pg|
    pg.vm.hostname = "pg-1"
    pg.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.51"

    config.vm.provider "virtualbox" do |v|
      # v.linked_clone = true
      v.check_guest_additions = false
    end
  end

  config.vm.define "pg-2" do |pg|
    pg.vm.hostname = "pg-2"
    pg.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.52"

    config.vm.provider "virtualbox" do |v|
      # v.linked_clone = true
      v.check_guest_additions = false
    end
  end

  config.vm.define "pg-3" do |pg|
    pg.vm.hostname = "pg-3"
    pg.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.53"

    config.vm.provider "virtualbox" do |v|
      # v.linked_clone = true
      v.check_guest_additions = false
    end
  end

  # config.vm.define "hap-1" do |hap|
  #   hap.vm.hostname = "hap-1"
  #   hap.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.41"

  #   config.vm.provider "virtualbox" do |v|
  #     # v.linked_clone = true
  #     v.check_guest_additions = false
  #   end
  # end

  # config.vm.define "hap-2" do |hap|
  #   hap.vm.hostname = "hap-2"
  #   hap.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.42"

  #   config.vm.provider "virtualbox" do |v|
  #     # v.linked_clone = true
  #     v.check_guest_additions = false
  #   end
  # end
end
