apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.56.1:3260
     iqn: iqn.2024-06.net.dasong.pg:disk01
     lun: 1
     fsType: ext4
     readOnly: false
     chapAuthDiscovery: false
     chapAuthSession: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.56.1:3260
     iqn: iqn.2024-06.net.dasong.pg:disk02
     lun: 1
     fsType: ext4
     readOnly: false
     chapAuthDiscovery: false
     chapAuthSession: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.56.1:3260
     iqn: iqn.2024-06.net.dasong.pg:disk03
     lun: 1
     fsType: ext4
     readOnly: false
     chapAuthDiscovery: false 
     chapAuthSession: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv4
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: 192.168.56.1:3260
     iqn: iqn.2024-06.net.dasong.pg:disk04
     lun: 1
     fsType: ext4
     readOnly: false
     chapAuthDiscovery: false
     chapAuthSession: false
