# Vagrant.configure("2") do |config|
#   config.vm.box = "hashicorp/bionic64"
# end

$script = <<-'SCRIPT'
# kubelet requires swap off
sudo swapoff -a
# keep swap off after reboot
sudo sed -i 's/\/swap/#&/' /etc/fstab

sudo systemctl disable ufw

sudo lvextend -l +100%FREE -r /dev/ubuntu-vg/ubuntu-lv


cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# sysctl params required by setup, params persist across reboots
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

sudo sysctl --system

# cilium
CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
CLI_ARCH=amd64
if [ "$(uname -m)" = "aarch64" ]; then CLI_ARCH=arm64; fi
curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}

SCRIPT

$k8s = <<-'SCRIPT'

sudo apt-get update
# apt-transport-https may be a dummy package; if so, you can skip that package
sudo apt-get install -y apt-transport-https ca-certificates curl gpg

# If the directory `/etc/apt/keyrings` does not exist, it should be created before the curl command, read the note below.
# sudo mkdir -p -m 755 /etc/apt/keyrings
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

# This overwrites any existing configuration in /etc/apt/sources.list.d/kubernetes.list
echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

sudo systemctl enable --now kubelet

SCRIPT

$containerd = <<-'SCRIPT'
sudo apt-get remove docker docker-engine docker.io containerd runc

# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

sudo chmod a+r /etc/apt/keyrings/docker.gpg
sudo apt-get update
sudo apt-get install containerd.io

# sudo apt-get update && sudo apt-get install -y containerd

sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml
sudo systemctl restart containerd

#wget https://github.com/containernetworking/plugins/releases/download/v1.5.0/cni-plugins-linux-amd64-v1.5.0.tgz
#sudo mkdir -p /opt/cni/bin
#sudo tar Cxzvf /opt/cni/bin cni-plugins-linux-amd64-v1.5.0.tgz

SCRIPT

# This defines the version of vagrant
Vagrant.configure(2) do |config|
  # Specifying the box we wish to use
    config.vm.box = "bento/ubuntu-22.04"
  # Adding Bridged Network Adapter
  # config.vm.network "public_network"
  # config.vm.network "private_network", :type => 'dhcp'

  config.vm.define "node-1" do |node|
    node.vm.hostname = "node-1"
    node.vm.network "private_network", ip: "192.168.56.13"

    config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.check_guest_additions = false

      v.memory = 3000
      v.cpus = 2
    end

    node.vm.provision "shell", inline: $script
    node.vm.provision "shell", inline: $containerd
    node.vm.provision "shell", inline: $k8s
  end

  config.vm.define "node-2" do |node|
    node.vm.hostname = "node-2"
    node.vm.network "private_network", ip: "192.168.56.14"

    config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.check_guest_additions = false

      v.memory = 3000
      v.cpus = 2
    end

    node.vm.provision "shell", inline: $script
    node.vm.provision "shell", inline: $containerd
    node.vm.provision "shell", inline: $k8s
  end

  config.vm.define "node-3" do |node|
    node.vm.hostname = "node-3"
    node.vm.network "private_network", ip: "192.168.56.15"

    config.vm.provider "virtualbox" do |v|
      v.linked_clone = true
      v.check_guest_additions = false

      v.memory = 3000
      v.cpus = 2
    end

    node.vm.provision "shell", inline: $script
    node.vm.provision "shell", inline: $containerd
    node.vm.provision "shell", inline: $k8s
  end
end
