# This defines the version of vagrant
Vagrant.configure(2) do |config|
  # Specifying the box we wish to use
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.define "m-1" do |node|
    node.vm.hostname = "m-1"
    node.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.11"
    # node.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |v|
      # v.linked_clone = true
      v.check_guest_additions = false

      v.memory = 3000
      v.cpus = 2
    end
  end

  config.vm.define "w-1" do |node|
    node.vm.hostname = "w-1"
    node.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.21"
    # node.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |v|
      # v.linked_clone = true
      v.check_guest_additions = false

      v.memory = 3000
      v.cpus = 2
    end
  end

  config.vm.define "w-2" do |node|
    node.vm.hostname = "w-2"
    node.vm.network "public_network", bridge: "wlp0s20f3", ip: "192.168.8.22"
    # node.vm.network "private_network", type: "dhcp"

    config.vm.provider "virtualbox" do |v|
      # v.linked_clone = true
      v.check_guest_additions = false

      v.memory = 3000
      v.cpus = 2
    end
  end
end
