apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-client
  namespace: postgres-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pg-client
  template:
    metadata:
      labels:
        name: pg-client
    spec:
      containers:
        - name: pg-client
          image: perconalab/percona-distribution-postgresql:16
          imagePullPolicy: Always
          command:
          - sleep
          args:
          - "100500"
          volumeMounts:
            - name: ca
              mountPath: "/tmp/tls"
      volumes:
      - name: ca
        secret:
          secretName: cluster1-pg-db-cluster-cert
          items:
          - key: ca.crt
            path: ca.crt
            mode: 0777
